version: '3.4'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - node.attr.box_type=hot
      - cluster.initial_master_nodes=es01,es02,es03
      - node.roles=master,data_content,data_hot
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - node.labels.lbes01==true
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - node.attr.box_type=warm
      - node.roles=master,data_warm
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - node.labels.lbes02==true
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - node.roles=master
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
    deploy:
      placement:
        constraints:
          - node.labels.lbes03==true
  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.0
    hostname: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - elastic
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
networks:
  elastic:
    driver: overlay
    internal: true
